title:              Guilherme's Blog
email:              guilhermevinche@gmail.com
description:        Just more one tech blog, where the focus is IAM, Integration and Architecture
author:             Guilherme Vinche
baseurl:            "/"
url:                "http://127.0.0.1:4000"

# Social Profiles
github_username:    guilhermevinche
linkedin_username:  joseguilhermevinche

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
